name: Smoke Testin For Infra and Networking

on:
  workflow_dispach:

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo " build and push successfully ✔"