name: Smoke Testinfg for infra and networking

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::824353504367:role/github-oidc-role
          aws-region: ap-south-1

      - name: Upload smoke_test.py on AWS
        run:
          aws s3 cp smoke_test.py \
          s3://566565555555555555-devops-sripts/smoke_test.py \
          --region ap-south-1

      - name: Run Smoke Test on Fleet
        id: smoke
        run:
          CMD_ID=$(aws ssm send-command \)
          --targets "key=tag:App,Values=flask"\
          --document-name "AWS-RunShellScript" |
          --parameters '{"commands":[
            '']}'