name: Test Fleet health and Env Variables

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::824353504367:role/github-action-deploy-role
          aws-region: ap-south-1

      - name: Fleet Health Checks
        id: health
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":[
              "hostname -I",
              "docker --version 2>/dev/null || echo Docker not installed",
              "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
              "mysql --version 2>/dev/null || echo mysql not Installed",
              "aws ssm get-parameter-by-path --path /application /application/banking --with-decryption --region ap-south-1"
              ]}' \
            --query 'Command.CommandId' --output text \
            --region ap-south-1)

          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT

      - name: Show Results
        run: |
          sleep 20

          aws ssm list-command-invocations \
            --command-id "${{ steps.health.outputs.cmd_id }}" \
            --details \
            --region ap-south-1 \
            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,IP:CommandPlugins[0].Output}" \
            --output table

          FAILED=$(aws ssm list-command-invocations \
            --command-id "${{ steps.health.outputs.cmd_id }}" \
            --details \
            --query "length(CommandInvocations[?Status=='Failed'])" \
            --output text \
            --region ap-south-1)

          [ "$FAILED" -gt 0 ] && \
          echo "::error::Health Check Failed on $FAILED instances" && \
          exit 1

          echo "ALL Instances Healthy ✅"